field: 7553dbab-3bd5-49d1-9f77-871da95f3431
fieldLayouts:
  d6a0f313-65d0-4dbe-9373-739141b60ec4:
    tabs:
      -
        elements:
          -
            fieldUid: 5d7959a5-445f-4fe0-be6f-a8bb356024e8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8ff2e815-5729-4266-9cf8-d896d252e89f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51c8e223-503c-475c-840d-009f0b050841
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  51c8e223-503c-475c-840d-009f0b050841:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'A caption for the asset (optional).'
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5d7959a5-445f-4fe0-be6f-a8bb356024e8:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'A headline for this block section (optional).'
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8ff2e815-5729-4266-9cf8-d896d252e89f:
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: ''
    name: Assets
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: asset
name: Asset
sortOrder: 2
