field: 7553dbab-3bd5-49d1-9f77-871da95f3431
fieldLayouts:
  633079e0-8f32-447c-a2ed-bde96368f94d:
    tabs:
      -
        elements:
          -
            fieldUid: 3f1a1b82-1576-414f-9a1a-a6c9a163f574
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83e6cfa2-5ded-4050-9926-670c5cd4b22b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27cd976d-4db2-4385-b1c9-1c491389c1dd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  27cd976d-4db2-4385-b1c9-1c491389c1dd:
    contentColumnType: string
    fieldGroup: null
    handle: assets
    instructions: 'One or more images to accompany the text.'
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  3f1a1b82-1576-414f-9a1a-a6c9a163f574:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Headline for combo section entry.'
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  83e6cfa2-5ded-4050-9926-670c5cd4b22b:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '8'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: combo
name: Combo
sortOrder: 3
