field: 051bd850-c36d-45b8-8d98-a7f00e6c8101
fieldLayouts:
  3a683aaf-3a99-4f55-84ee-f3ee827f7849:
    tabs:
      -
        elements:
          -
            fieldUid: 64e1e664-c7bf-4c5a-bd1f-d68aaa5732aa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f77be19a-7196-4b72-a7d8-c5dc9c8afb48
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 79219040-5944-42d5-9fa9-cb9f6f014c24
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 46fcd7d6-3b63-4cd5-a30a-125314166ccc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5332f9b-25d6-43b6-adad-55e3877881f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ec453e18-8cdd-41e6-b599-44474544ab38
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: daf49672-e777-49ce-9be0-e111a99d2194
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eeccb6eb-4070-40f0-8234-3f0e4155422e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  46fcd7d6-3b63-4cd5-a30a-125314166ccc:
    contentColumnType: string
    fieldGroup: null
    handle: libraryItem
    instructions: ''
    name: 'Library Item'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select library item to link.'
      showSiteMenu: true
      source: null
      sources:
        - 'section:77d9d325-ab7a-436e-af66-b061daec1973'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  64e1e664-c7bf-4c5a-bd1f-d68aaa5732aa:
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: 'category name'
    name: Category
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  79219040-5944-42d5-9fa9-cb9f6f014c24:
    contentColumnType: string
    fieldGroup: null
    handle: cover
    instructions: 'Cover image, gif, or video.'
    name: Cover
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fa75faff-05c7-48a8-9f68-e71f7f6f6264'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5332f9b-25d6-43b6-adad-55e3877881f8:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Caption for item. Can be multi-line.'
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  daf49672-e777-49ce-9be0-e111a99d2194:
    contentColumnType: string(7)
    fieldGroup: null
    handle: textMainColor
    instructions: 'Main color for text. This will default to all colors if set. If secondary color is set this will only color the label and title.'
    name: 'Text Main Color'
    searchable: false
    settings:
      defaultColor: '#000000'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  ec453e18-8cdd-41e6-b599-44474544ab38:
    contentColumnType: string(7)
    fieldGroup: null
    handle: primaryColor
    instructions: 'Main color for the background of this curated display'
    name: 'Primary Color'
    searchable: false
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  eeccb6eb-4070-40f0-8234-3f0e4155422e:
    contentColumnType: string(7)
    fieldGroup: null
    handle: textSecondaryColor
    instructions: 'If set this will color the description and player colors. If not set these colors will default to the Text Main Color'
    name: 'Text Secondary Color'
    searchable: false
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  f77be19a-7196-4b72-a7d8-c5dc9c8afb48:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Title of library item or other headline description.'
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: libraryItem
name: 'Library Item'
sortOrder: 1
