field: 7553dbab-3bd5-49d1-9f77-871da95f3431
fieldLayouts:
  ece59147-2143-4500-a558-e799e84653dd:
    tabs:
      -
        elements:
          -
            fieldUid: d0ba7bff-b79e-4397-8afd-d72e685f3ec5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2d305ea4-6d8a-4a4b-9e9a-6f509ba11613
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2d305ea4-6d8a-4a4b-9e9a-6f509ba11613:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Enter main text for this content block.'
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '8'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d0ba7bff-b79e-4397-8afd-d72e685f3ec5:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Headline for section (optional).'
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
