contentColumnType: string(7)
fieldGroup: 7a2ab025-d6b5-4d32-af07-56bbaa748841
handle: altAccentColor
instructions: 'Alternative accent color for effect or emphasis.'
name: 'Alternate Accent Color'
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
