contentColumnType: boolean
fieldGroup: 7a2ab025-d6b5-4d32-af07-56bbaa748841
handle: animatedHeaderToggle
instructions: 'Turn the animated header on or off'
name: 'Animated Header Toggle'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
