contentColumnType: string(7)
fieldGroup: 7a2ab025-d6b5-4d32-af07-56bbaa748841
handle: baseColor
instructions: 'Background color for site pages'
name: 'Base Color'
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
