contentColumnType: string(7)
fieldGroup: 7a2ab025-d6b5-4d32-af07-56bbaa748841
handle: socialLinksColor
instructions: 'Color for social Links'
name: 'Social Links Color'
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
