fieldLayouts:
  d68ca2e8-5338-4edc-9196-0f77649d415c:
    tabs:
      -
        elements:
          -
            fieldUid: 585198e1-656c-4e55-8589-f00dd32f81b4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6f6076c-fd2b-4f6f-a97d-835a1281d8d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f0c0bc8-7058-4a5e-9c24-4e68adeed244
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20e8a4e4-5884-4648-a681-ca811be8703f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e1ccbae-afe0-40dd-805c-9a5b9ee869fd
            instructions: ''
            label: 'Transparent Header'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b313fc2-00be-4a97-a339-0c905fd8577d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 76bd4683-8d26-466a-83dc-c84e6e2d37c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19714df2-fe6e-404a-a686-2bf24c4c5f28
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4283ee36-a673-406f-8c6c-9a5c2645aec2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b4e45db-e2d1-4ec4-a472-e3759ec085ca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'site colors'
        sortOrder: 1
handle: colors
name: Colors
