enableVersioning: true
handle: callToActionLinks
name: 'Call To Action Links'
propagationMethod: all
siteSettings:
  16577b9f-37cc-4fe5-ab94-920c3ae062b4:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'call-to-action-links/{slug}'
type: channel
