enableVersioning: true
handle: libraryAudio
name: 'Library Entry'
propagationMethod: all
siteSettings:
  16577b9f-37cc-4fe5-ab94-920c3ae062b4:
    enabledByDefault: true
    hasUrls: true
    template: _components/librarby/page
    uriFormat: 'library/{slug}'
type: channel
